# -*- coding: utf-8 -*-
"""lab11b_f.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Sr7DkjCFH-PUjmC1fV1zdwbHoXLXLNc
"""

!pip install -q sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss

# --- Step 1: Prepare documents ---
docs = [
    "The Taj Mahal is located in Agra, India.",
    "The Eiffel Tower is a famous landmark in Paris, France.",
    "The Great Wall of China was built for defense and stretches over 13,000 miles.",
]

# --- Step 2: Create embeddings ---
model = SentenceTransformer('all-MiniLM-L6-v2')  # Small, fast embedding model
doc_embeddings = model.encode(docs)

# --- Step 3: Create FAISS index ---
dimension = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(doc_embeddings)

# --- Step 4: Define retrieval function ---
def retrieve(query, top_k=2):
    query_emb = model.encode([query])
    distances, indices = index.search(query_emb, top_k)
    return [docs[i] for i in indices[0]]

# --- Step 5: Ask questions ---
query = "Where is the Taj Mahal located?"
retrieved_docs = retrieve(query)

print("Question:", query)
print("Retrieved Documents:")
for doc in retrieved_docs:
    print("-", doc)

